### PR TITLE
Remove alpha channel from PNG

### LINKED ISSUE #124: uv fails rendering png with transparent alpha channel
Reported in Hyrax by @jmfrenzel [uv fails rendering png with transparent alpha channel](https://github.com/samvera/hyrax/issues/3422)

### Descriptive summary

Universal viewer (uv) fails rendering png with transparent alpha channel as well as uv download is providing corrupt jpg version 

### Expected behavior
uv should provide original png download link and render (if needed) jpg correctly

### Actual behavior
https://nurax-dev.curationexperts.com/concern/images/hd76s024f?locale=en#?c=0&m=0&s=0&cv=0&xywh=-2%2C0%2C290%2C99

### Steps to reproduce the behavior

1. https://nurax-dev.curationexperts.com/concern/images/hd76s024f?locale=en#?c=0&m=0&s=0&cv=0&xywh=-2%2C0%2C290%2C99Do this

### Related

PR #123 fixed a similar issue with PDF, see https://github.com/curationexperts/riiif/blob/master/app/services/riiif/imagemagick_command_factory.rb#L100

### PR DESCRIPTION
**Pull request by geekscruff**
Fixes #124 

As reported in [hyrax#3422](https://github.com/samvera/hyrax/issues/3422). 

The solution to the immediate Hyrax issue woule be to request png as the transformation format where the source was png (and had an alpha channel). But ... Universal Viewer seems to ignore the format set in the manifest and requests jpg anyway. 

So, to ensure we retain the alpha channel, this PR now does the following:

1) checks for the existentence of an alpha channel (using the info_service output)
2) if there is an alpha channel, add the `-alpha on` flag to the convert command to ensure it is retained
3) override the transformation format to be png where there is an alpha channel and the transformation format is jpg (since jpg can't support this)

The obvious problem here is that we could be (and would be in the case of Universal Viewer requests) returning a different format to that requested, however UV seems to be already doing the same.

There will be a companion Hyrax PR to add 'channels' to the info_service output.

### CODE REVIEW

**Comment by geekscruff** [comment]
@jcoyne @bess your eyes on this would be much appreciated, it fixes an issue identified in Hyrax. My only question would be whether this could have a negative impact elsewhere?

**Comment by jcoyne** [comment]
the IIIF image spec recommends that the server supports transparency:

> For rotations which are not multiples of 90 degrees, it is recommended that the client request the image in a format that supports transparency, such as PNG, and that the server return the image with a transparent background. There is no facility in the API for the client to request a particular background color or other fill pattern.


So, I think this would go against that.

**Comment by geekscruff** [comment]
@jcoyne thanks Justin, I've revised the PR to add support for alpha channels. The potentially contentious bit of this is returning png in cases where there is an alpha channel. I would really appreciate your feedback on this. Thanks!

File: app/services/riiif/imagemagick_command_factory.rb [hunk 1]
```diff
@@ -64,9 +68,15 @@ def input
         " #{path}#{layer_spec}"
       end
 
+      # In cases where the input file has an alpha_channel but the transformation
+      #   format is 'jpg', change to 'png' as jpeg does not support alpha channels
       # pipe the output to STDOUT
       def output
-        " #{transformation.format}:-"
+        if alpha_channel? && jpeg?
+          " png:-"
```
Comment (jcoyne) [inline app/services/riiif/imagemagick_command_factory.rb]: Can you add a test for this case?

Comment (geekscruff) [reply app/services/riiif/imagemagick_command_factory.rb]: Done. Thanks for the quick response. Would you be OK to merge?

**Comment by jcoyne** [comment]
@geekscruff sorry, just one more change.  Can you title the commit to be `Remove alpha channel from PNG `. because that was I can tell what this is when I do `git log` without having to rely on github.

**Comment by geekscruff** [comment]
@jcoyne Done!
